; Generated by Auto-GUI 3.0.1
#SingleInstance Force
    #NoEnv 
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Button, ggo x176 y192 w120 h22, Give me code
Gui Add, Edit, vusername x24 y40 w120 h21, github_username 
Gui Add, Edit, vrepository x24 y88 w120 h21, github_repository 
Gui Add, DropDownList, vdrop x176 y88 w120, Object-based||function-based
Gui Add, Edit, vFile x24 y136 w122 h21, File_DL_Name
Gui Add, Text, x176 y136 w186 h23 +0x200, Choose a name for saving locally
Gui Add, Button, greset x24 y192 w80 h22, Reset

Gui Show, w370 h259, Use AHK to download Github Latest Releases
Return

go:
    GuiControlGet, repository
    GuiControlGet, username
    GuiControlGet, file
    GuiControlGet, drop
    array := [repository, username, drop, file]
    obj := new Code(array)
    DisplayLog(obj.full(), obj.req())  
Return

reset:
Return

Class Code {
    __New(array) {
        this.repo := array[1]
        this.user := array[2]
        this.drop := array[3]
        this.file := array[4]
    }
    combine() {
        rep := `"""" this.repo "/" this.user `"""" 
        return rep
    } 
    
    baseline() {
        val=
(
#Include Json.ahk    ;place in same dir as code
#Include github.ahk  ;place in same dir as code 
#SingleInstance, force
    #NoEnv

)
        return val
    }
    
    req() {
        file :=  this.combine()
        script := this.file
        necessary= 
(
;keep this above download object
repos := %File%
git := new Github(repos)

;starts downloading github release
git.DL("%script%")
)
        return necessary 
    }
    
    full() {
        code := this.baseline() "`n" this.req()
        return code
    }
    
}


DisplayLog(FullCode, Partial) {

  global
  Gui new, hwndOne 
  Gui show, w364 h291, Code
  Gui Font, s9, Segoe UI
  Gui Add, Edit, vfull x16 y40 w143 h183
  Gui Add, Edit, vpatrial x176 y40 w143 h183
  Gui Add, Text, x25 y8 w120 h23 +0x200, Full
  Gui Add, Text, x176 y8 w120 h23 +0x200, Partial
  Gui Add, Button, gfuller x48 y240 w80 h23, Copy
  Gui Add, Button, gpatrialer x208 y240 w80 h23, Copy
    GuiControl,, full, %fullcode%
    GuiControl,, patrial, %Partial%
    Return
  
  fuller:
  clipboard := obj.full()
  return
  
   patrialer:
   clipboard := obj.req()
   return
  
  
  
  }

GuiEscape:
GuiClose:
    ExitApp
    